// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqhfo4kRTkJi8YecN6GVgLml5cDZ8YJdk',
    appId: '1:669133426887:web:bdf5edf9bdb3b4efc62ee2',
    messagingSenderId: '669133426887',
    projectId: 'sota-snake-game',
    authDomain: 'sota-snake-game.firebaseapp.com',
    storageBucket: 'sota-snake-game.appspot.com',
    measurementId: 'G-TDRZJ6N3ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWJtH9C33OpWAUEQcwM7oXEwSH2AS2MY',
    appId: '1:669133426887:android:f4394fc0587b27e8c62ee2',
    messagingSenderId: '669133426887',
    projectId: 'sota-snake-game',
    storageBucket: 'sota-snake-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWRaPjx9XQ3p06z-pQtdAxaDNJObApPNI',
    appId: '1:669133426887:ios:83f093fe9a13dd40c62ee2',
    messagingSenderId: '669133426887',
    projectId: 'sota-snake-game',
    storageBucket: 'sota-snake-game.appspot.com',
    iosBundleId: 'com.truthysystems.sota',
  );
}
